### PR TITLE
Make sure all data gets stored on disable

### PR DESCRIPTION
**Pull request by rjworks**
Make sure all data gets stored on disable

### CODE REVIEW

**Comment by rjworks** [comment]
any side effects if another plugin is saving data and has waitAll() in onDisable()?

**Comment by Shock95x** [comment]
It's already used here https://github.com/Shock95x/AuctionHouse/blob/388cb0bc7d1d83c83f398a1ae7c58991ce4e5fe0/src/shock95x/auctionhouse/database/Database.php#L111

**Comment by Shock95x** [comment]
I don't think there are any side effects to that also

**Comment by rjworks** [comment]
oh oops

**Pull request closed without merging**
